
const SOURCE_LABELS={pexels:'Pexels',pixabay:'Pixabay',unsplash:'Unsplash',youtube:'YouTube reference',canva:'Canva',coverr:'Coverr',mixkit:'Mixkit',videvo:'Videvo',freepik:'Freepik',stocksnap:'StockSnap',burst:'Burst',pikwizard:'Pikwizard',lifeofpix:'Life of Pix'};
const ALL=Object.keys(SOURCE_LABELS); const STOP=new Set('the a an and or but of to in on for with from by as is are was were this that these those it its into about after before while where when what why how can could should would will just your you they them their has have had not no yes more most very really nobody wants wanted want vehicle vehicles video media search source direct results missing found open show use using'.split(' '));
function json(x,s=200){return new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'}})}
function clean(x){return String(x||'').replace(/[^\w\s.,?!:$%&()'"/+-]/g,' ').replace(/\s+/g,' ').trim()}
function kw(t,n=8){const f=new Map();for(const w of clean(t).toLowerCase().replace(/\b(2026|2025|2024)\b/g,' ').split(/\s+/).filter(w=>w.length>2&&!STOP.has(w)))f.set(w,(f.get(w)||0)+1);return[...f.entries()].sort((a,b)=>b[1]-a[1]).slice(0,n).map(x=>x[0])}
function niche(n){return{general:'cinematic documentary b roll',automotive:'cars trucks vehicle dealership mechanic engine',aviation:'aircraft airplane airport cockpit runway',business:'business finance office charts',technology:'technology computers data AI',finance:'finance money banking stock market charts',construction:'construction site workers machinery',nature:'nature forest ocean mountains wildlife',documentary:'documentary real footage news evidence'}[n]||'cinematic documentary b roll'}
function query(text,topic='',n='general'){return `${kw(topic+' '+text).join(' ')||clean(topic+' '+text).slice(0,80)} ${niche(n)}`.trim()}
function item(source,type,title,url='',downloadUrl='',thumb='',meta=''){return{source,type,title:clean(title).slice(0,160)||source,url,downloadUrl,thumbnail:thumb,meta}}
function fallback(source,q){const e=encodeURIComponent(q);const links={Pexels:`https://www.pexels.com/search/videos/${e}/`,Pixabay:`https://pixabay.com/videos/search/${e}/`,Unsplash:`https://unsplash.com/s/photos/${e}`,'YouTube reference':`https://www.youtube.com/results?search_query=${e}`,YouTube:`https://www.youtube.com/results?search_query=${e}`,Canva:`https://www.canva.com/templates/?query=${e}`,Coverr:`https://coverr.co/s?q=${e}`,Mixkit:`https://mixkit.co/free-stock-video/`,Videvo:`https://www.videvo.net/search/${e}/`,Freepik:`https://www.freepik.com/search?format=search&query=${e}`,StockSnap:`https://stocksnap.io/search/${e}`,Burst:`https://burst.shopify.com/photos/search?utf8=%E2%9C%93&q=${e}`,Pikwizard:`https://pikwizard.com/search/${e}/`,'Life of Pix':`https://www.lifeofpix.com/search/${e}/`};return item(source,'source search',`Open ${source} search for "${q}"`,links[source]||'','','','Source search link. Open it to preview/download manually.')}
function dedupe(a,max=999){const seen=new Set(),out=[];for(const x of a){const k=x.downloadUrl||x.url||x.title;if(!k||seen.has(k))continue;seen.add(k);out.push(x);if(out.length>=max)break}return out}
async function pexels(q,c,env){if(!env.PEXELS_API_KEY)return[];let out=[];try{let r=await fetch(`https://api.pexels.com/videos/search?query=${encodeURIComponent(q)}&per_page=${c}`,{headers:{authorization:env.PEXELS_API_KEY}});if(r.ok){let d=await r.json();for(const v of d.videos||[]){const f=(v.video_files||[]).find(x=>x.file_type==='video/mp4');if(f)out.push(item('Pexels','video',`Pexels video ${v.id}`,v.url,f.link,v.image,'Direct MP4'))}}}catch{}return dedupe(out,c)}
async function pixabay(q,c,env){if(!env.PIXABAY_API_KEY)return[];let out=[];try{let r=await fetch(`https://pixabay.com/api/videos/?key=${env.PIXABAY_API_KEY}&q=${encodeURIComponent(q)}&per_page=${c}&safesearch=true`);if(r.ok){let d=await r.json();for(const x of d.hits||[]){const v=x.videos?.medium||x.videos?.small;if(v)out.push(item('Pixabay','video',x.tags,x.pageURL,v.url,'',x.user))}}}catch{}return dedupe(out,c)}
async function unsplash(q,c,env){if(!env.UNSPLASH_ACCESS_KEY)return[];try{let r=await fetch(`https://api.unsplash.com/search/photos?query=${encodeURIComponent(q)}&per_page=${c}`,{headers:{authorization:`Client-ID ${env.UNSPLASH_ACCESS_KEY}`}});if(!r.ok)return[];let d=await r.json();return dedupe((d.results||[]).map(x=>item('Unsplash','photo',x.alt_description||'Unsplash photo',x.links.html,x.urls.raw,x.urls.small,x.user?.name||'')),c)}catch{return[]}}
async function youtube(q,c,env){if(!env.YOUTUBE_API_KEY)return[];try{let r=await fetch(`https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&safeSearch=moderate&q=${encodeURIComponent(q)}&maxResults=${c}&key=${env.YOUTUBE_API_KEY}`);if(!r.ok)return[];let d=await r.json();return dedupe((d.items||[]).map(x=>item('YouTube reference','reference',x.snippet?.title,`https://www.youtube.com/watch?v=${x.id?.videoId}`,'',x.snippet?.thumbnails?.medium?.url,x.snippet?.channelTitle)),c)}catch{return[]}}
async function openverse(q,c){try{let r=await fetch(`https://api.openverse.engineering/v1/images/?q=${encodeURIComponent(q)}&page_size=${c}`);if(!r.ok)return[];let d=await r.json();return dedupe((d.results||[]).map(x=>item('Openverse','photo',x.title,x.foreign_landing_url||x.url,x.url,x.thumbnail,x.license)),c)}catch{return[]}}
async function nasa(q,c){try{let r=await fetch(`https://images-api.nasa.gov/search?q=${encodeURIComponent(q)}&media_type=image`);if(!r.ok)return[];let d=await r.json();return dedupe((d.collection?.items||[]).slice(0,c).map(x=>item('NASA','photo',x.data?.[0]?.title,x.href,x.links?.[0]?.href,x.links?.[0]?.href,'NASA')),c)}catch{return[]}}
async function source(id,q,c,env){if(id==='canva')return[fallback('Canva',q)];const funcs={pexels, pixabay, unsplash, youtube, openverse, nasa};const name=SOURCE_LABELS[id];if(!funcs[id])return[fallback(name,q)];const res=await funcs[id](q,c,env);return res.length?res:[fallback(name,q)]}
async function searchAll(q,c,sources,env){c=Math.max(1,Math.min(+c||3,20));const groups={};for(const id of (sources?.length?sources:ALL)){const name=SOURCE_LABELS[id];groups[name]=await source(id,q,c,env)}return{query:q,groups,keys:status(env)}}
function status(env){return{PEXELS_API_KEY:!!env.PEXELS_API_KEY,PIXABAY_API_KEY:!!env.PIXABAY_API_KEY,UNSPLASH_ACCESS_KEY:!!env.UNSPLASH_ACCESS_KEY,YOUTUBE_API_KEY:!!env.YOUTUBE_API_KEY,FLICKR_API_KEY:!!env.FLICKR_API_KEY,GIPHY_API_KEY:!!env.GIPHY_API_KEY}}
function time(s){const p=s.split(':').map(Number);return p.length===2?p[0]*60+p[1]:p[0]*3600+p[1]*60+p[2]}function fmt(n){n=Math.round(n);return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function parse(script,topic,n){return String(script||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map((line,i)=>{const m=line.match(/^[\[(]?(\d{1,2}:\d{2}(?::\d{2})?)[\])]?\s*(?:[-–—:|]\s*)?(.*)$/);if(!m)return null;const text=clean(m[2]);const timestamp=m[1].length===4?'0'+m[1]:m[1];return{scene:i+1,timestamp,text,query:query(text,topic,n),canvaTerms:[`${kw(topic+' '+text,5).join(' ')} ${n} cinematic`,`${kw(topic+' '+text,5).join(' ')} dark title card`],visualPlan:'Use relevant B-roll, title card, chart, or evidence screenshot.',textCallout:text.includes('?')?text.slice(0,50).toUpperCase():''}}).filter(Boolean)}
function sfx(text,timestamp){const l=text.toLowerCase();let cat='Transition',use='Use light whoosh at scene change.',terms=['subtle transition whoosh','soft cinematic whoosh'];if(/failure|risk|warning|panic|problem|collapse/.test(l)){cat='Impact';use='Use low boom on key word.';terms=['low cinematic boom','dark tension impact']}if(/million|billion|%|percent|price|inventory|sales|\\$/.test(l)){cat='Data';use='Use clean data ping on number.';terms=['data ping sound effect','clean UI click data']}return{category:cat,use,volume:'8–15%',timing:`${timestamp} + 0.0s`,sources:terms.flatMap(t=>[item('Pixabay Sound Effects','sound effect',t,`https://pixabay.com/sound-effects/search/${encodeURIComponent(t)}/`),item('Freesound','sound effect',t,`https://freesound.org/search/?q=${encodeURIComponent(t)}`)]).slice(0,4)}}
function musicPlan(scenes,topic,n){const q=`${topic||n} documentary background music no vocals`;return{mainMood:'Serious documentary',sources:[item('Pixabay Music','background music',q,`https://pixabay.com/music/search/${encodeURIComponent(q)}/`),item('Mixkit','background music',q,'https://mixkit.co/free-stock-music/'),item('YouTube Audio Library','background music',q,'https://studio.youtube.com/channel/UC/music')]}};
export async function onRequest(context){return json({ok:true,keys:status(context.env)})}