
const SOURCE_LABELS={pexels:'Pexels',pixabay:'Pixabay',unsplash:'Unsplash',youtube:'YouTube reference',canva:'Canva',coverr:'Coverr',mixkit:'Mixkit',videvo:'Videvo',freepik:'Freepik',stocksnap:'StockSnap',burst:'Burst',pikwizard:'Pikwizard',lifeofpix:'Life of Pix',pinterest:'Pinterest'};
const ALL=Object.keys(SOURCE_LABELS);
const STOP=new Set('the a an and or but of to in on for with from by as is are was were this that these those it its into about after before while where when what why how can could should would will just your you they them their has have had not no yes more most very really nobody wants wanted want vehicle vehicles video media search source direct results missing found open show use using'.split(' '));
function json(x,s=200){return new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'}})}
function clean(x){return String(x||'').replace(/[^\w\s.,?!:$%&()'"\/+-]/g,' ').replace(/\s+/g,' ').trim()}
function kw(t,n=8){const f=new Map();for(const w of clean(t).toLowerCase().replace(/\b(2026|2025|2024)\b/g,' ').split(/\s+/).filter(w=>w.length>2&&!STOP.has(w)))f.set(w,(f.get(w)||0)+1);return [...f.entries()].sort((a,b)=>b[1]-a[1]).slice(0,n).map(x=>x[0])}
function niche(n){return{general:'cinematic documentary b roll',automotive:'cars trucks vehicle dealership highway pickup engine',aviation:'aircraft airplane airport cockpit runway',business:'business finance office charts',technology:'technology computers data AI',finance:'finance money banking stock market charts',construction:'construction site workers machinery',nature:'nature forest ocean mountains wildlife',documentary:'documentary real footage news evidence',motivation:'motivational cinematic people success city',history:'historical archive documentary'}[n]||'cinematic documentary b roll'}
function buildTerms(text,topic='',n='general'){const k=kw(topic+' '+text,8);const primary=`${k.join(' ')||clean(topic+' '+text).slice(0,80)} ${niche(n)}`.trim();const secondary=`${k.slice(0,5).join(' ')||clean(text).slice(0,50)} close up b roll`.trim();return [primary,secondary]}
function canvaTerms(text,topic='',n='general'){const k=kw(topic+' '+text,6);return [`${k.join(' ')} Canva video template`.trim(),`${k.join(' ')} dark title card`.trim()]}
function textCallout(text=''){const c=clean(text).slice(0,140);const m=c.match(/(\$?\d[\d,.]*\s?(million|billion|thousand|%|percent|days|years|hours|vehicles|trucks|cars)?)/i);if(m)return `${m[0].trim().toUpperCase()} MATTERS`;if(c.includes('?'))return c.split('?')[0].slice(0,56).toUpperCase()+'?';return c.split(/[,.]/)[0].slice(0,56).toUpperCase()}
function item(source,type,title,url='',downloadUrl='',thumb='',meta=''){return{source,type,title:clean(title).slice(0,160)||source,url,downloadUrl,thumbnail:thumb,meta}}
function normalizeUrl(u=''){try{let x=String(u||'').trim(); if(!x) return ''; x=x.replace(/^http:\/\//,'https://'); x=x.split('#')[0]; if(!/youtube\.com\/watch/.test(x)) x=x.split('?')[0]; return x.replace(/\/$/,'');}catch{return String(u||'')}}
function mediaKey(x){const a=normalizeUrl(x.downloadUrl); const b=normalizeUrl(x.url); const c=normalizeUrl(x.thumbnail); return a||b||c||`${x.source}:${(x.title||'').toLowerCase().trim()}`}
function dedupe(arr,max=999,used=null){const seen=new Set(), out=[]; for(const m of arr||[]){const k=mediaKey(m); if(!k||seen.has(k)||used?.has(k)) continue; seen.add(k); if(used) used.add(k); out.push(m); if(out.length>=max) break;} return out;}
function linkSource(source,q){const e=encodeURIComponent(q); const links={Pexels:`https://www.pexels.com/search/videos/${e}/`,Pixabay:`https://pixabay.com/videos/search/${e}/`,Unsplash:`https://unsplash.com/s/photos/${e}`,'YouTube reference':`https://www.youtube.com/results?search_query=${e}`,Canva:`https://www.canva.com/templates/?query=${e}`,Coverr:`https://coverr.co/s?q=${e}`,Mixkit:`https://mixkit.co/free-stock-video/`,Videvo:`https://www.videvo.net/search/${e}/`,Freepik:`https://www.freepik.com/search?format=search&query=${e}`,StockSnap:`https://stocksnap.io/search/${e}`,Burst:`https://burst.shopify.com/photos/search?utf8=%E2%9C%93&q=${e}`,Pikwizard:`https://pikwizard.com/search/${e}/`,'Life of Pix':`https://www.lifeofpix.com/?s=${e}`,Pinterest:`https://www.pinterest.com/search/pins/?q=${e}`}; return item(source, source==='Pinterest'?'reference':'search', `${source} search: ${q}`, links[source]||'', '', '', source==='Pinterest'?'Reference / inspiration':'Open source search');}
async function searchPexels(q,c,env){if(!env.PEXELS_API_KEY) return []; let out=[]; try{const r=await fetch(`https://api.pexels.com/videos/search?query=${encodeURIComponent(q)}&per_page=${Math.min(c,20)}`,{headers:{authorization:env.PEXELS_API_KEY}}); if(r.ok){const d=await r.json(); for(const v of d.videos||[]){const f=(v.video_files||[]).filter(x=>x.file_type==='video/mp4').sort((a,b)=>(b.width||0)-(a.width||0))[0]; if(f) out.push(item('Pexels','video',`Pexels video ${v.id}`,v.url,f.link,v.image,'Direct MP4'));}}}catch{} return dedupe(out,c)}
async function searchPixabay(q,c,env){if(!env.PIXABAY_API_KEY) return []; let out=[]; try{const r=await fetch(`https://pixabay.com/api/videos/?key=${env.PIXABAY_API_KEY}&q=${encodeURIComponent(q)}&per_page=${Math.min(c,20)}&safesearch=true`); if(r.ok){const d=await r.json(); for(const x of d.hits||[]){const v=x.videos?.large||x.videos?.medium||x.videos?.small; if(v?.url) out.push(item('Pixabay','video',x.tags||`Pixabay video ${x.id}`,x.pageURL,v.url,'',x.user||'Pixabay'));}}}catch{} return dedupe(out,c)}
async function searchUnsplash(q,c,env){if(!env.UNSPLASH_ACCESS_KEY) return []; try{const r=await fetch(`https://api.unsplash.com/search/photos?query=${encodeURIComponent(q)}&per_page=${Math.min(c,20)}&orientation=landscape`,{headers:{authorization:`Client-ID ${env.UNSPLASH_ACCESS_KEY}`}}); if(!r.ok) return []; const d=await r.json(); return dedupe((d.results||[]).map(x=>item('Unsplash','photo',x.alt_description||x.description||'Unsplash photo',x.links?.html||'',x.urls?.raw||'',x.urls?.small||'',x.user?.name||'')),c)}catch{return []}}
async function searchYouTube(q,c,env){if(!env.YOUTUBE_API_KEY) return []; try{const r=await fetch(`https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&safeSearch=moderate&q=${encodeURIComponent(q)}&maxResults=${Math.min(c,20)}&key=${env.YOUTUBE_API_KEY}`); if(!r.ok) return []; const d=await r.json(); return dedupe((d.items||[]).map(x=>item('YouTube reference','reference',x.snippet?.title||'YouTube video',`https://www.youtube.com/watch?v=${x.id?.videoId||''}`,'',x.snippet?.thumbnails?.medium?.url||'',x.snippet?.channelTitle||'')),c)}catch{return []}}
async function source(id,q,c,env){if(id==='pexels') return (await searchPexels(q,c,env)); if(id==='pixabay') return (await searchPixabay(q,c,env)); if(id==='unsplash') return (await searchUnsplash(q,c,env)); if(id==='youtube') return (await searchYouTube(q,c,env)); return [linkSource(SOURCE_LABELS[id],q)];}
async function searchAllForQuery(q,c,sources,env,used=null){const groups={}; for(const id of (sources?.length?sources:ALL).filter(x=>SOURCE_LABELS[x])){const label=SOURCE_LABELS[id]; groups[label]=dedupe(await source(id,q,c,env),c,used);} return groups;}
async function searchScene(terms,c,sources,env,used){const combined={}; for(const t of terms){const groups=await searchAllForQuery(t,c,sources,env,used); for(const [name,items] of Object.entries(groups)){combined[name]=combined[name]||[]; for(const m of items){const kk=mediaKey(m); if(!combined[name].some(x=>mediaKey(x)===kk)){combined[name].push(m); if(combined[name].length>=c) break;}}}}
 for(const name of Object.keys(combined)){combined[name]=combined[name].slice(0,c);} return combined;}
function parseScript(script,topic,n){return String(script||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map((line,i)=>{const m=line.match(/^[\[(]?(\d{1,2}:\d{2}(?::\d{2})?)[\])]?(?:\s*[-–—:|]\s*|\s+)(.*)$/) || line.match(/^[\[(]?(\d{1,2}:\d{2}(?::\d{2})?)[\])]?(.*)$/); if(!m) return null; const text=clean(m[2]); if(!text) return null; const terms=buildTerms(text,topic,n); return {scene:i+1,timestamp:m[1],text,query:terms[0],mediaSearchTerms:terms,canvaTerms:canvaTerms(text,topic,n),textCallout:textCallout(text),sfx:sfx(text)};}).filter(Boolean)}
function audioItem(source,type,title,url,meta=''){return item(source,type,title,url,'','',meta)}
function musicPlan(topic,n){const q=`${topic||n} documentary background music no vocals`; return {mainMood:'Serious documentary',sources:[audioItem('Pixabay Music','background music',q,`https://pixabay.com/music/search/${encodeURIComponent(q)}/`),audioItem('Mixkit','background music',q,'https://mixkit.co/free-stock-music/'),audioItem('YouTube Audio Library','background music',q,'https://studio.youtube.com/channel/UC/music')]}}
function sfx(text=''){const l=text.toLowerCase(); let category='Transition', use='Use a soft whoosh between scenes.', terms=['subtle transition whoosh','soft cinematic whoosh']; if(/failure|warning|risk|panic|problem|collapse|crash/.test(l)){category='Impact'; use='Use a low boom or dark hit on the key point.'; terms=['low cinematic boom','dark impact hit'];} if(/million|billion|%|percent|price|inventory|sales|\$/.test(l)){category='Data'; use='Use a clean data ping on the number.'; terms=['data ping','clean UI click'];} return {category,use,terms,sources:[audioItem('Pixabay Sound Effects','sound effect',terms[0],`https://pixabay.com/sound-effects/search/${encodeURIComponent(terms[0])}/`),audioItem('Freesound','sound effect',terms[1],`https://freesound.org/search/?q=${encodeURIComponent(terms[1])}`)]}}
export async function onRequest(context){if(context.request.method==='OPTIONS')return json({});try{const b=await context.request.json(); const scenes=parseScript(b.script,b.topic||'',b.niche||'general'); if(!scenes.length) return json({error:'No valid timestamps found. Use 00:00 Sentence format.'},400); const used=new Set(); for(const s of scenes){s.media={groups: await searchScene(s.mediaSearchTerms, Math.max(1,Math.min(+b.count||3,20)), b.sources||ALL, context.env, used)};} const backgroundMusic=musicPlan(b.topic||'',b.niche||'general'); const report=['STRICT NO-REPEAT MODE: ON','BACKGROUND MUSIC',...backgroundMusic.sources.map(x=>x.source+': '+x.url),'',...scenes.map(s=>`${s.timestamp} ${s.text}
Media Terms: ${(s.mediaSearchTerms||[]).join(' | ')}
Canva: ${(s.canvaTerms||[]).join(' | ')}
SFX: ${s.sfx.category} - ${s.sfx.use}
`).join('
')]; return json({ok:true,total:scenes.length,scenes,backgroundMusic,report:report.join('
')});}catch(e){return json({error:e.message},500)}}